# Generated by Django 5.2.11 on 2026-02-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='شمارهٔ یکتای رزرو مثلاً SC-ABC123-01', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_passenger', models.BooleanField(default=False)),
                ('has_baggage', models.BooleanField(default=False)),
                ('has_vehicle', models.BooleanField(default=False)),
                ('passenger_name', models.CharField(blank=True, max_length=255)),
                ('passenger_id_number', models.CharField(blank=True, max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('baggage_pieces', models.PositiveIntegerField(blank=True, null=True)),
                ('baggage_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('baggage_items', models.JSONField(blank=True, default=list)),
                ('vehicle_items', models.JSONField(blank=True, default=list)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=32)),
                ('vehicle_type', models.CharField(blank=True, max_length=64)),
                ('vehicle_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('origin_port', models.CharField(max_length=64)),
                ('destination_port', models.CharField(max_length=64)),
                ('departure_date', models.DateTimeField()),
                ('document_type', models.CharField(choices=[('PASSENGER_TICKET', 'Passenger Ticket'), ('CARGO_BOARDING_CARD', 'Cargo Boarding Card')], default='CARGO_BOARDING_CARD', max_length=32)),
                ('departure_gate', models.CharField(blank=True, max_length=32)),
                ('seat_number', models.CharField(blank=True, max_length=32)),
                ('seating_area', models.CharField(blank=True, max_length=32)),
                ('arrival_date', models.CharField(blank=True, max_length=64)),
                ('carrier_name', models.CharField(blank=True, max_length=128)),
                ('ticket_number', models.CharField(blank=True, max_length=64)),
                ('sequence_number', models.CharField(blank=True, max_length=32)),
                ('boarding_time', models.CharField(blank=True, max_length=32)),
                ('user', models.ForeignKey(blank=True, help_text='کاربری که این رزرو را ثبت کرده (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
    ]
