# Generated by Django 5.2.11 on 2026-02-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passport_number',
            field=models.CharField(blank=True, help_text='شماره پاسپورت مسافر', max_length=64),
        ),
    ]
